WHAT WE WILL COVER HERE --

1)creating tensors 
2)Getting information from tensors (tensor attributes)
3) Manipulating tensors (tensor operations)
4) Tensors and NumPy
5) Using @tf.function 
6) Using GPUs with TensorFlow
    






In [ ]:
# tensorflow basics 1

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)   #version of tensorflow

2.5.0


In [ ]:
#creating tensors using tf.constant

In [ ]:
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim  # to see no of dimensions   #note ---- scalar has 0 dimension always

0

In [ ]:
# create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#to check  dimension of vector
vector.ndim   #vector has 1 dimension always

1

In [ ]:
#create matrix
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim   # matrix has 2 dimension always

2

In [ ]:
m=tf.constant([[10.,7.],[3.,9.],[6.,2,]] , dtype=tf.float16 )

In [ ]:
m

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  9.],
       [ 6.,  2.]], dtype=float16)>

In [ ]:
m.ndim

2

In [ ]:
mm=tf.constant([[10.,7.,3.],[3.,9.,2.],[6.,2.,55.]] , dtype=tf.float16 )
mm

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  7.,  3.],
       [ 3.,  9.,  2.],
       [ 6.,  2., 55.]], dtype=float16)>

In [ ]:
mm.ndim

2

In [ ]:
# now to n dimensions we create tensor, lets see
tensor=tf.constant([[[1,2,3],
                     [4,5,6]]
                    ,[[7,8,8],
                      [10,11,12]]
                    ,[[13,14,15],
                      [16,17,18]]
                    ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  8],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# points to remember 
# scalar : a single num
# vector : a number with direction
# matrix : 2 d array of nums
# tensor : a n dimensional array of num ( o dim tensor is a scalar, 1  dim tensor is a vector, 2 dim vector is a matrix)




In [ ]:
# creating tensors with tf.variable

tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
c=tf.Variable([10,7])
u=tf.constant([10,7])
c, u

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
c[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
c[0]=7

TypeError: ignored

In [ ]:
# as we got error by assigning value at a particular index of changable tensor ..c , so lets use assign() now 
c[0].assign(7)
c

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# when we try to change unchangable tensor 
u[0]=8

TypeError: ignored

In [ ]:
u[0].assign(7)
u

AttributeError: ignored

In [ ]:
# so this is the difference between tf.constant and tf.variable  as we can see this above as per our requirements we can use any type of tensor ..constant or variable

In [ ]:
# creating random tensors

# random tensors are tensors of some arbitrary size which contain random numbers

# 1) create two random but same tensors

r1=tf.random.Generator.from_seed(42)
r1=r1.normal(shape=(3,2))

r2=tf.random.Generator.from_seed(42)
r2=r2.normal(shape=(3,2))

#are they both equal ?

r1,r2,r1==r2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# shuffling the order of elements in a tensors

# this is needed bcz say eg i have 10k images of ramen and 5k maggi so now tensor will try to look more like ramen bcz more data of ramen is there ,
# so we need to mix maggi patterns also by shuffling

not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# randomly shuffles a tensor along its first direction

#shuffle our non suffled tensor

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# getting reproducable shuffled aura
tf.random.set_seed(42)  #global seed
tf.random.shuffle(not_shuffled,seed=42)  # operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, r1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# note ---- below we can see if we set seed at operational level then we get different output each time

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# note -- if we set global seed  , we will get same output everytime 

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# imp -- it looks like if we want our shuffled tensors to be in same order , we have to set both global and operational level seed

In [ ]:
####### SOME OTHER WAYS TO CREATE TENSORS

In [ ]:

tf.ones(3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [ ]:
tf.ones([11,3])

<tf.Tensor: shape=(11, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([3,5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,6))

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

# we can also change numpy arrays into tensors
the main difference between numpy and tensorflow tensors is that tensors can be run very fastly on GPU

In [ ]:
import numpy as np
a=np.arange(1,25,dtype=np.int32)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a_A=tf.constant(a)
a_A  # yipeeeee !!! i converted numpy array into tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
b=tf.constant(a,shape=(2,3,4))
c=tf.constant(a)
b,c

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
# imppp --- the parameters in shape ie 2,3,4 in above eg ...should result in same output.. 2*3*4 = 24 ..as 24 num are to be rearranged 

In [ ]:
# attributes of tensor -- shape,rank,axis,size( total no of items in tensor)

In [ ]:
# create a rank 4 tensor ( 4 dimension )
rank_4=tf.zeros(shape=[2,3,4,5])
rank_4

####### vvvv.. impp --- here 2,3,4,5 means 
# 2- 2 tensors of same type with 3,4,5 ,3 - no of tensor inside each tensor is 3 ...4 - no of rows , 5 - no of columns 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4.shape , rank_4.ndim, tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# size = 120 bcz 2*3*4*5 = 120 , dim = 4 as ( 2,3,4,5) ie 4 elements , 

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4.dtype) 
print("Number of dimensions (rank):", rank_4.ndim)
print("Shape of tensor:", rank_4.shape)
print("Elements along axis 0 of tensor:", rank_4.shape[0])
print("Elements along last axis of tensor:", rank_4.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


  ### indexing and expanding tensors 

In [ ]:
# get first two elementsof each dimension 
rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element  from each dimension from each index except for the final one
rank_4[:1,:1,:1,:5]


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# create rank 2 tensor with 2 dimension 

rank_2=tf.constant([[1,2],[11,21]])
rank_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [11, 21]], dtype=int32)>

In [ ]:
rank_2.ndim

2

In [ ]:
# get last element of each row 
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 21], dtype=int32)>

In [ ]:
###### impppppp -- adding extra dimension to our existing tensor 

rank_3=rank_2[...,tf.newaxis]   # here ... means every axis before the last one (rank_3=rank_2[:,:,tf.newaxis] )
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2]],

       [[11],
        [21]]], dtype=int32)>

In [ ]:
# alternative of tf.newaxis

tf.expand_dims(rank_2,axis=-1)  # -1 means here to expand the final axis 




<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2]],

       [[11],
        [21]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2,axis=0)  

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [11, 21]]], dtype=int32)>

### tensor operations ... (manipulating tensors)

In [ ]:
#basic operations - +,-,*,\

In [ ]:
tensor=tf.constant([[2,4],[8,9]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 14],
       [18, 19]], dtype=int32)>

In [ ]:
# orignal tensor is unchanged 

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [8, 9]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 40],
       [80, 90]], dtype=int32)>

In [ ]:
tensor-6

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -2],
       [ 2,  3]], dtype=int32)>

In [ ]:
## we can use inbuit functions also for these operations

In [ ]:
tf.multiply(tensor,9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 36],
       [72, 81]], dtype=int32)>

### matrix multiplication

In [ ]:
print(tensor)

tf.Tensor(
[[2 4]
 [8 9]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor,tensor)  # matmul for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 36,  44],
       [ 88, 113]], dtype=int32)>

In [ ]:
tensor*tensor  # different from matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 16],
       [64, 81]], dtype=int32)>

In [ ]:
t1=tf.constant([[1,2,5],[7,2,1],[3,3,3]])
t1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [ ]:
t2=tf.constant([[3,5],[6,7],[1,8]])
t2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [ ]:
tf.matmul(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
t1.shape

TensorShape([3, 3])

In [ ]:
t1@t2   # use @ instead of matmul to get same results 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# we can't multiply matrices of different dimensions 

In [ ]:
# info of matrix multiplication--- https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# rules -- the inner dimensions must match and  resulting  matrix has shape of inner dimensions 

In [ ]:
x=tf.constant([[1,2],[3,4],[5,6]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
y=tf.constant([[7,8],[9,10],[11,12]])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
tf.matmul(x,y)

InvalidArgumentError: ignored

In [ ]:
# as we got error above so try to reshape matrix by matrix rules 

In [ ]:
# change shapeof y

tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
x.shape , tf.reshape(y,shape=(2,3)).shape  # inner dim are same so correct

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
 # try changing sha[pe of x instead of y
 tf.reshape(x, shape=(2,3)) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.reshape(x,shape=(2,3)).shape , y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

### we can do the same with transpose 

*   it flips the axis


In [ ]:
x,tf.transpose(x) , tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### dot product 
matrix mul is also called dot product

perform this using -
tf.matmul()

tf.tensordot(x,y,axes= '',name=None) -tensor contaction of x and y along specified axes and outer product

In [ ]:
## perform dot product on x and y

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
## perform matrix multiplication between x and y (transposed)

tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [87]:
y,tf.reshape(y,shape=(2,3)),tf.transpose(y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

### changing the datatype of a tensor

In [88]:
b=tf.constant([1.9,11.])
b.dtype

tf.float32

In [89]:
i=tf.constant([1,2])
i.dtype

tf.int32

In [ ]:
# now we want to change  default float32 to float16 (reduced precision)
 
 # by using mixed precision ie .. 16 and 32 bit floating point types in a model we cam make it run faster and use less memory . by keeping some parts  of model 
 # 32 bit  , the model wil have a lower step time and more accuracuy .     
 # in lower precision dtypes like float 16 bfloat16 ,modern accelerators can run operations faster in 16 bit datatypes , as they have specialized
 #hardware to run on 16 bit computations and 16 bit dtypes can read from memory faster 


In [91]:
bb=tf.cast(b,dtype=tf.float16)
bb

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1.9, 11. ], dtype=float16)>

In [92]:
b.dtype, bb.dtype

(tf.float32, tf.float16)

In [94]:
e=tf.cast(a,dtype=tf.float32)
e

<tf.Tensor: shape=(24,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)>

In [95]:
e.dtype

tf.float32

#### aggregating tensors  ...means condensing tensors from multiple values down to a smaller amt of values



In [96]:
# get the absolute values

d=tf.constant([-8,-4])
d


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-8, -4], dtype=int32)>

In [98]:
tf.abs(d) ## get absolute value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 4], dtype=int32)>

In [ ]:
## forms of aggregation -- get min , max, mean,sum of tensor

In [102]:
randdom=tf.constant(np.random.randint(0,100,size=50))

In [105]:
randdom

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([87,  6, 28, 78, 20, 56,  2, 90, 99, 70, 74, 78, 33, 38, 48, 48, 93,
       23,  4, 50, 83, 34, 71, 70,  5, 98, 55, 46, 35, 73,  1, 23, 71, 59,
       61, 92, 48, 20, 61,  8, 48, 56, 75, 14, 83, 44, 16, 69, 24, 49])>

In [106]:
tf.size(randdom) , randdom.shape , randdom.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [107]:
## to get minimum from above tensor

tf.reduce_min(randdom)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [108]:
tf.reduce_max(randdom)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [109]:
tf.reduce_mean(randdom)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [110]:
tf.reduce_sum(randdom)

<tf.Tensor: shape=(), dtype=int64, numpy=2517>

In [119]:
x = tf.constant([[1., 2.], [3., 4.]])


##### calculating variance 


In [120]:
tf.math.reduce_variance(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.25>

In [117]:

tf.math.reduce_variance(x, 0)




<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [118]:
tf.math.reduce_variance(x, 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.25, 0.25], dtype=float32)>

In [121]:
#### calculating standard deviation  tf.math.reduce_std(input_tensor, axis=None, keepdims=False, name=None)

tf.math.reduce_std(x)




<tf.Tensor: shape=(), dtype=float32, numpy=1.118034>

In [122]:

tf.math.reduce_std(x, 0)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [123]:


tf.math.reduce_std(x, 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5, 0.5], dtype=float32)>

In [124]:
### other methodd

import tensorflow_probability as tfp

In [125]:
tfp.stats.variance(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [128]:
# to find standard deviation 
tf.math.reduce_std(tf.cast(randdom,dtype=tf.float32)) 
## bcz reduce_std requires real or complex tensor

<tf.Tensor: shape=(), dtype=float32, numpy=28.149323>

## find the positional maximum and minimum of a tensor

In [ ]:
#to find that  at which  position the max /min value exists in a particular roww /column 

In [132]:
tf.random.set_seed(42)
f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [136]:
tf.argmax(f)  ## returns max value across axes of a tensor
## returns index of max value in tensor

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [137]:
# to get max value in tensor
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [138]:
# get max val of f
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [139]:
f[tf.argmax(f)]==tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [142]:
# find the positional minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [143]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# squeezing a tensor ---- removing all single dimensions

In [145]:
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [146]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [148]:
g_squeezed = tf.squeeze(g)
g.shape,g_squeezed,g_squeezed.shape

(TensorShape([1, 1, 1, 1, 50]), <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### one hot encoding tensors

In [153]:
l=[0,1,2,2] # red,green,blue,purple

tf.one_hot(l,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [156]:
l=[0,1,2,1] # red,green,blue,purple

tf.one_hot(l,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]], dtype=float32)>

In [157]:
l=[0,1,2,2] # red,green,blue,purple

tf.one_hot(l,depth=6)

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)>

In [158]:
#specify custom values for one hot encoding
tf.one_hot(l,depth=4,on_value="dl is fun",off_value="dsa is fun too")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'dl is fun', b'dsa is fun too', b'dsa is fun too',
        b'dsa is fun too'],
       [b'dsa is fun too', b'dl is fun', b'dsa is fun too',
        b'dsa is fun too'],
       [b'dsa is fun too', b'dsa is fun too', b'dl is fun',
        b'dsa is fun too'],
       [b'dsa is fun too', b'dsa is fun too', b'dl is fun',
        b'dsa is fun too']], dtype=object)>

some more operations on tensors

In [ ]:
# squaring , log,square root

In [159]:
h=tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [160]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [164]:
tf.sqrt(tf.cast(h,dtype=tf.float32))  ## sqrt requires non int type input

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [168]:
tf.math.log(tf.cast(h,dtype=tf.float32))  ## requies . math

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

TENSORS AND NUMPY

In [169]:
j=tf.constant(np.array([1.09,2.99]))
j

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.09, 2.99])>

In [170]:
## convert tensor back to numpy 

np.array(j) ,type(np.array(j))

(array([1.09, 2.99]), numpy.ndarray)

In [172]:
# convert tensor j to a numpy array
j.numpy()

array([1.09, 2.99])

In [173]:
type(j.numpy())

numpy.ndarray

In [174]:
j=tf.constant([3.])
j

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>

In [175]:
j.numpy()[0]

3.0

In [176]:
# default types of each are slightly different
n_j=tf.constant(np.array([3.,7.,10.]))
t_j=tf.constant([3.,7.,10.])
# check dtypes 
n_j.dtype , t_j.dtype

(tf.float64, tf.float32)

finding access to GPUs

In [177]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [178]:
tf.config.list_physical_devices("GPU")

[]

TO GET FREE ACCESS TO GPUs ---  runtime->  change runtime type -> free GPU s ( nvidia k80 s , t4s , P4s , P100s) -> select GPU -> save 

In [3]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
!nvidia-smi  # v fast gpu


Sun Aug  1 14:41:08 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P8    25W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# ** IMPP ____ IF YOU HAVE ACCESS TO A CUDA ENABLED GPU , TENSORFLOW WILL AUTOMATICALLY USE IT WHENEVER POSSIBLE**